### ISSUE TITLE
Artwork is revealed when dragging

### ISSUE THREAD

**Issue by avgurf** [guytepper/album-hangman#15]
Artwork images can be dragged (also by mistake) and reveal the unblurred album picture:
![image](https://user-images.githubusercontent.com/8542480/31233421-4641d092-a9f5-11e7-9add-fdd894c0f604.png)

I also think right clicking on the image should also be prevented - in case someone tries to open the image in a new window or tab or to save it (I guess it will prevent most players from cheating 😉)

**Comment by guytepper** [comment]
I think preventing right click on the image is an overkill.. the idea of the game is to have fun, if someone wants to cheat then why would he play? 🤡
With that being said I think that preventing image drag would be great.

**Comment by avgurf** [comment]
Players can still cheat, this isn't cheat-proof, it just became a bit harder. I personally find having the option to easily right-click the image and see what it was, without actually loosing, kinda tempting, I have to admit (I'm a terrible person I know). Bottom line I did do it, once (ok more than once), so I believe making it harder for me to cheat will make the game more fun to others as well, and also it could make a better ground for a future scoring system maybe?🤔
