### ISSUE TITLE
Albums repeat far too often

### ISSUE THREAD

**Issue by jakeledoux** [guytepper/album-hangman#44]
Sometimes you'll even get the same one twice in a row.

**Comment by guytepper** [comment]
Hi! Thanks for reporting :-)
I couldn't manage to replicate the issue. Tried with my & my friend's Spotify account and both times it worked fine - a new random album has been generated each time.

Would you mind helping me trace the issue? I'd like to see how many albums are being retrieved from  the Spotify API (I'm guessing that this is the service you're using?)

**Comment by jakeledoux** [comment]
Your Spotify question confused me for a moment, but now I think I know what's going on.
I was using [this website](http://album-hangman.surge.sh/) which uses your Last.fm username to grab the albums. On the homepage it has a single Github icon that points here. I assumed this was just the repo for that site but now I'm realizing that the guy who made that just probably cloned this repo, replaced the Spotify integration with Last.fm, and left the github link the same.

If that's correct then I apologize, I'm reporting this bug to the wrong person. That guy's gotta add some text like "forked from this project" or something.

Cheers.

**Comment by jakeledoux** [comment]
Damn I just played your official version (on your website not cloned, and authenticated with Spotify) and I'm still having the same issue with repeats. Guess the issue isn't irrelevant after all.

What can I do to help?

**Comment by jakeledoux** [comment]
I just played 25 rounds and wrote down the albums so you have an idea of what the issue looks like. Here it is:

> - Gunship - GUNSHIP
> - Carpenter Brut - Trilogy
> - Carpenter Brut - Leather Teeth
> - Tenacious D - Tenacious D
> - Max Compulsion - Axed
> - Dream Theater - Black Clouds and Silver Linings
> - Tenacious D - Rize of the Fenix
> - Gunship - Dark All Day
> - Dream Theater - Train of Thought
> - Carpenter Brut - Leather Teeth
> - Tenacious D - Tenacious D
> - Dream Theater - Black Clouds and Silver Linings
> - Gunship - Dark All Day
> - Max Compulsion - Axed
> - Carpenter Brut - Leather Teeth
> - Tenacious D - Rize of the Fenix
> - Carpenter Brut - CARPENTERBRUTLIVE
> - Tenacious D - Rize of the Fenix
> - Carpenter Brut - CARPENTERBRUTLIVE
> - Gunship - Dark All Day
> - Gunship - GUNSHIP
> - Carpenter Brut - Leather Teeth
> - FM-84 - Atlas
> - Gunship - GUNSHIP
> - Tenacious D - The Pick of Destiny

**Comment by guytepper** [comment]
Thanks for taking the time to help :-) 
Actually, it was an old domain that I've used. It uses an old version of the game which had Last.fm support instead of Spotify. I'll redirect it to the new domain.

The game [generates a random album](https://github.com/guytepper/album-hangman/blob/master/src/views/Game/Game.js#L66) from the albums it receives from the API. 
I suspect that the albums are repeated frequently because the API responds with a small amount of albums. 

Can you open the developer tools network tab while on the game page, hit refresh, find one of the requests that has `albums?limit=50&offset=` in their name and tell me what is the `total` value in it's response? 

<img width="735" alt="screen shot 2019-02-08 at 23 38 45" src="https://user-images.githubusercontent.com/13344923/52508050-f3e27100-2bfb-11e9-9893-818b18ce7004.png">

**Comment by jakeledoux** [comment]
Oddly the total is only 13. I know for a fact that I've got far more albums saved then that, especially if it includes singles (which I do see in the JSON response).

I've just done the same request in the Spotify Web Console and it also returns 13, meaning there must be something to do with my specific profile that's not right. I wonder what Spotify qualifies as a "saved album". Perhaps I have to had clicked save on the album itself rather than saving the songs individually.

Would it be too much to ask to have your site instead look at the tracks in your library and read the albums that the tracks belong to, rather than just asking for albums directly? I imagine that impact the performance though.

**Comment by jakeledoux** [comment]
What's weird about the album thing is that some of the albums are ones that I haven't saved in their entirety. For instance, I've only saved the first track off "Dream Theater - Train of Thought" and yet it's still one of the returned albums. The mystery continues...

**Comment by guytepper** [comment]
Strange. I can see the total number goes up only when saving a whole album; it stays the same when saving a single track. 
Can you try saving a whole album and see if it affects the total number?

**Comment by jakeledoux** [comment]
Seems to be the case. Even if you save each song individually the album isn't added. If you save the album and then unsave all the individual tracks, it counts the album regardless. A dumb system IMO.

**Comment by guytepper** [comment]
I agree /: Guess we'll have to work with that. 

Thanks for the report and your help 💕this is actually the 2nd time that someone reported about the issue and now we've got an explanation (-:
